version: '3.4'

services:
  postgres:
    image: postgres:12.1
    restart: always
    ports:
      - 5432:5432
    hostname: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keystone
