org: sebastianandreasson
app: sebastianandreasson-com
service: sebastianandreasson-com

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-north-1

functions:
  next:
    handler: handler.run
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
