name: 'sebastianandreasson-com'

website:
  component: serverless-next.js
  inputs:
    domain: ['test', 'sebastianandreasson.com']
# functions:
#   next:
#     handler: handler.run
#     events:
#       - http:
#           path: /
#           method: ANY
#       - http:
#           path: /{any+}
#           method: ANY
